# https://testdriven.io/blog/github-actions-docker/
# https://github.com/youssefbrr/self-hosted-runner/blob/main/docker-compose.yml
services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETOS: "${TARGETOS}"
        RUNNER_CLI_VERSION: "${RUNNER_CLI_VERSION}"
        UBUNTU_RELEASE: "${UBUNTU_RELEASE}"
        CONTAINER_USER: "${CONTAINER_USER}"
        CONTAINER_GROUP: "${CONTAINER_GROUP}"
        CONTAINER_USER_ID: "${CONTAINER_USER_ID}"
        CONTAINER_GROUP_ID: "${CONTAINER_GROUP_ID}"
        WORKSPACE_ROOT_DIR: "${WORKSPACE_ROOT_DIR}"
    platform: "linux/amd64"
    privileged: true
    restart: always
    environment:
      - GH_TOKEN
      - GH_API_VERSION
      - GH_API_URI_PREFIX
      - RUNNER_SCOPE_PREFIX
      - RUNNER_SCOPE
      - RUNNER_NAME
      - RUNNER_GROUP_NAME
      - RUNNER_LABELS
      - WORKSPACE_ROOT_DIR
    image: "${CONTAINER_REPOSITORY}${CONTAINER_IMAGE_NAME}${CONTAINER_IMAGE_TAG}"
    group_add:
      - docker
    stop_grace_period: 360s
    volumes:
      - /dev:/dev
    network_mode: "host"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M
