name: "Example of composite action"

runs:
  using: "composite"
  steps:
    - name: 'Run composite action'
      shell: bash
      run: echo "Running composite action arch=$(uname -m) runner_name=${{ runner.name }} on hostname=$(hostname)."
