name: 'Prepare multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
#  schedule:
#    - cron: "45 22 * * *"
#      timezone: 'Europe/Bratislava'
  workflow_dispatch:
    inputs:
      RUNNER_CLI_VERSION:
        description: 'RUNNER_CLI_VERSION'
        required: false
        type: string
        default: '2.335.1'
      ANT_VERSION:
        description: 'ANT_VERSION'
        required: false
        type: string
        default: '1.10.17'
      JDK_8_VERSION:
        description: 'JDK_8_VERSION'
        required: false
        type: string
        default: '8.0.492-tem'
      JDK_21_VERSION:
        description: 'JDK_21_VERSION'
        required: false
        type: string
        default: '21.0.11-tem'
      GRADLE_VERSION:
        description: 'GRADLE_VERSION'
        required: false
        type: string
        default: '9.6.1'
      GROOVY_VERSION:
        description: 'GROOVY_VERSION'
        required: false
        type: string
        default: '5.0.6'
      MAVEN_VERSION:
        description: 'MAVEN_VERSION'
        required: false
        type: string
        default: '3.9.16'
      KOTLIN_VERSION:
        description: 'KOTLIN_VERSION'
        required: false
        type: string
        default: '2.4.0'
      CONTAINER_TAG:
        description: 'CONTAINER_TAG (text)'
        required: false
        type: string
        default: 'initial'
      SKIP_VERSION_CHANGE:
        description: 'SKIP_VERSION_CHANGE'
        required: false
        type: boolean
        default: false

env:
  GH_REGISTRY: ghcr.io
  DH_REGISTRY: docker.io

jobs:
  docker-build-test-tag-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-26.04]
    permissions:
      contents: write
      packages: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Set requested tools versions to GITHUB_ENV'
        shell: bash
        run: |
          export DH_USER="${{ secrets.DH_USER }}"; export DH_TOKEN="${{ secrets.DH_TOKEN }}"; export GH_PERSONAL_TOKEN="${{ secrets.GH_TOKEN }}"; export GH_TOKEN_ORG="${{ secrets.GH_TOKEN_ORG }}"; ./setvariables.sh
          echo "CONTAINER_TAG=initial" >> ${GITHUB_ENV}
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.RUNNER_CLI_VERSION }}" != "" ]]; then
              sed -i "s/RUNNER_CLI_VERSION=.*/RUNNER_CLI_VERSION=${{ github.event.inputs.RUNNER_CLI_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.ANT_VERSION }}" != "" ]]; then
              sed -i "s/ANT_VERSION=.*/ANT_VERSION=${{ github.event.inputs.ANT_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.JDK_8_VERSION }}" != "" ]]; then
              sed -i "s/JDK_8_VERSION=.*/JDK_8_VERSION=${{ github.event.inputs.JDK_8_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.JDK_21_VERSION }}" != "" ]]; then
              sed -i "s/JDK_21_VERSION=.*/JDK_21_VERSION=${{ github.event.inputs.JDK_21_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.GRADLE_VERSION }}" != "" ]]; then
              sed -i "s/GRADLE_VERSION=.*/GRADLE_VERSION=${{ github.event.inputs.GRADLE_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.GROOVY_VERSION }}" != "" ]]; then
              sed -i "s/GROOVY_VERSION=.*/GROOVY_VERSION=${{ github.event.inputs.GROOVY_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.MAVEN_VERSION }}" != "" ]]; then
              sed -i "s/MAVEN_VERSION=.*/MAVEN_VERSION=${{ github.event.inputs.MAVEN_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.KOTLIN_VERSION }}" != "" ]]; then
              sed -i "s/KOTLIN_VERSION=.*/KOTLIN_VERSION=${{ github.event.inputs.KOTLIN_VERSION }}/g" /tmp/github_env_tail
            fi
            if [[ "${{ github.event.inputs.CONTAINER_TAG }}" != "" ]]; then
              sed -i "s/CONTAINER_TAG=.*/CONTAINER_TAG=${{ github.event.inputs.CONTAINER_TAG }}/g" >> ${GITHUB_ENV}
            fi
          fi
          if [[ "${{ github.event.inputs.SKIP_VERSION_CHANGE }}" == "false" ]]; then
            export DH_USER="${{ secrets.DH_USER }}"; export DH_TOKEN="${{ secrets.DH_TOKEN }}"; export GH_PERSONAL_TOKEN="${{ secrets.GH_TOKEN }}"; export GH_TOKEN_ORG="${{ secrets.GH_TOKEN_ORG }}"; ./setvariables.sh
          fi
          cat /tmp/github_env_tail >> ${GITHUB_ENV}
          echo "WORKSPACE_ROOT_DIR=/home/user" >> ${GITHUB_ENV}
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> ${GITHUB_ENV}
          echo "/tmp/github_env_tail:"
          cat /tmp/github_env_tail
          echo "GITHUB_ENV:"
          cat ${GITHUB_ENV}
      - name: 'Set up QEMU (arm64)'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' || github.event.inputs.SKIP_VERSION_CHANGE == 'true' }}
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/arm64
      - name: 'Set up Docker buildx'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' || github.event.inputs.SKIP_VERSION_CHANGE == 'true' }}
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          driver-opts: |
            network=host
            image=moby/buildkit:master
      - name: 'Login to GitHub Container Registry'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' || github.event.inputs.SKIP_VERSION_CHANGE == 'true' }}
        uses: docker/login-action@master
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
          ecr: false
          logout: true
      - name: 'Login to DockerHub Container Registry'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' || github.event.inputs.SKIP_VERSION_CHANGE == 'true' }}
        uses: docker/login-action@master
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
          ecr: false
          logout: true
      - name: 'Check GHCR package exists'
        id: pkg-check
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          count=$(gh api "/user/packages/container/${{ env.REPOSITORY_NAME }}/versions" --jq 'length' 2> /dev/null || echo 0)
          echo "count=$count" >> "${GITHUB_OUTPUT}"
      - name: 'Cleanup ${{ env.GH_REGISTRY }} registry'
        if: steps.pkg-check.outputs.count != '0'
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        uses: actions/delete-package-versions@main
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ env.REPOSITORY_NAME }}
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 2
      - name: 'Build multi-platforms Docker images'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' || github.event.inputs.SKIP_VERSION_CHANGE == 'true' }}
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            RUNNER_CLI_VERSION=${{ env.RUNNER_CLI_VERSION }}
            WORKSPACE_ROOT_DIR=${{ env.WORKSPACE_ROOT_DIR }}
          load: false
          provenance: false
          no-cache: false
          platforms: linux/amd64,linux/arm64
      - name: 'Tag and push multi-platforms Docker images to preconfigured container registries'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' || github.event.inputs.SKIP_VERSION_CHANGE == 'true' }}
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            RUNNER_CLI_VERSION=${{ env.RUNNER_CLI_VERSION }}
            ANT_VERSION=${{ env.ANT_VERSION }}
            JDK_8_VERSION=${{ env.JDK_8_VERSION }}
            JDK_21_VERSION=${{ env.JDK_21_VERSION }}
            GRADLE_VERSION=${{ env.GRADLE_VERSION }}
            GROOVY_VERSION=${{ env.GROOVY_VERSION }}
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}
            KOTLIN_VERSION=${{ env.KOTLIN_VERSION }}
            WORKSPACE_ROOT_DIR=${{ env.WORKSPACE_ROOT_DIR }}
          push: true
          provenance: false
          no-cache: false
          github-token: ${{ secrets.GH_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          tags: |
            ${{ env.GH_REGISTRY }}/${{ github.repository }}:${{ env.CONTAINER_TAG }}
            ${{ env.DH_REGISTRY }}/${{ secrets.DH_USER }}/${{ env.REPOSITORY_NAME }}:${{ env.CONTAINER_TAG }}
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          platforms: linux/amd64,linux/arm64
          outputs: |
            type=image,compression=gzip,compression-level=3,force-compression=true
      - name: 'Pull git'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' }}
        run: |
          git pull --rebase
      - name: 'Push git changes'
        if: ${{ env.CLI_VERSIONS_CHANGED == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
