name: 'Example reusable workflow'

on: workflow_call

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: ["ubuntu-latest","ubuntu-24.04-arm"]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Run task'
        shell: bash
        run: echo "Running composite action arch=$(uname -m) runner_name=${{ runner.name }} on hostname=$(hostname)."
